/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;


import Modelo.dao.ClienteDao;
import Modelo.entidad.Cliente;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author PERSONAL
 */
public class frmCliente extends javax.swing.JInternalFrame {

   ClienteDao clientedao = new ClienteDao();
    Cliente cliente = new Cliente();

    DefaultTableModel defaultTableModel = new DefaultTableModel();

    int id;
    public frmCliente() {
        initComponents();
        listarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtnombre = new LIB.FSTexFieldMD();
        btnIngresar1 = new LIB.FSButtonMD();
        btnActualizar = new LIB.FSButtonMD();
        btnNuevo = new LIB.FSButtonMD();
        txtapellidos = new LIB.FSTexFieldMD();
        jLabel11 = new javax.swing.JLabel();
        txtdireccion = new LIB.FSTexFieldMD();
        jLabel12 = new javax.swing.JLabel();
        txttelefono = new LIB.FSTexFieldMD();
        jLabel13 = new javax.swing.JLabel();
        txtdni = new LIB.FSTexFieldMD();
        jLabel14 = new javax.swing.JLabel();
        txtcorreo = new LIB.FSTexFieldMD();
        jLabel15 = new javax.swing.JLabel();
        btnEliminar = new LIB.FSButtonMD();
        jLabel16 = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID CLIENTE", "NOMBRES", "APELLIDOS", "DIRECCION", "TELEFONO", "DNI", "CORREO"
            }
        ));
        jtabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 20, 530, 310));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Registrar Cliente");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        txtnombre.setForeground(new java.awt.Color(0, 0, 0));
        txtnombre.setToolTipText("");
        txtnombre.setBordeColorFocus(new java.awt.Color(251, 204, 52));
        txtnombre.setBordeColorNoFocus(new java.awt.Color(204, 204, 204));
        txtnombre.setCaretColor(new java.awt.Color(204, 204, 204));
        txtnombre.setMaterialDesing(true);
        txtnombre.setPlaceholder("Ingrese Nombres");
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        btnIngresar1.setBackground(new java.awt.Color(255, 0, 0));
        btnIngresar1.setText("INGRESAR");
        btnIngresar1.setColorNormal(new java.awt.Color(255, 0, 0));
        btnIngresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, -1));

        btnActualizar.setBackground(new java.awt.Color(255, 0, 0));
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.setColorNormal(new java.awt.Color(255, 0, 0));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, -1, -1));

        btnNuevo.setBackground(new java.awt.Color(255, 0, 0));
        btnNuevo.setText("NUEVO");
        btnNuevo.setColorNormal(new java.awt.Color(255, 0, 0));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, -1, -1));

        txtapellidos.setForeground(new java.awt.Color(0, 0, 0));
        txtapellidos.setToolTipText("");
        txtapellidos.setBordeColorFocus(new java.awt.Color(251, 204, 52));
        txtapellidos.setBordeColorNoFocus(new java.awt.Color(204, 204, 204));
        txtapellidos.setCaretColor(new java.awt.Color(204, 204, 204));
        txtapellidos.setMaterialDesing(true);
        txtapellidos.setPlaceholder("Ingrese Apellidos");
        jPanel1.add(txtapellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Apellidos");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        txtdireccion.setForeground(new java.awt.Color(0, 0, 0));
        txtdireccion.setToolTipText("");
        txtdireccion.setBordeColorFocus(new java.awt.Color(251, 204, 52));
        txtdireccion.setBordeColorNoFocus(new java.awt.Color(204, 204, 204));
        txtdireccion.setCaretColor(new java.awt.Color(204, 204, 204));
        txtdireccion.setMaterialDesing(true);
        txtdireccion.setPlaceholder("Ingrese Direccion");
        jPanel1.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("Direccion");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        txttelefono.setForeground(new java.awt.Color(0, 0, 0));
        txttelefono.setToolTipText("");
        txttelefono.setBordeColorFocus(new java.awt.Color(251, 204, 52));
        txttelefono.setBordeColorNoFocus(new java.awt.Color(204, 204, 204));
        txttelefono.setCaretColor(new java.awt.Color(204, 204, 204));
        txttelefono.setMaterialDesing(true);
        txttelefono.setPlaceholder("Ingrese Telefono");
        jPanel1.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Telefono");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        txtdni.setForeground(new java.awt.Color(0, 0, 0));
        txtdni.setToolTipText("");
        txtdni.setBordeColorFocus(new java.awt.Color(251, 204, 52));
        txtdni.setBordeColorNoFocus(new java.awt.Color(204, 204, 204));
        txtdni.setCaretColor(new java.awt.Color(204, 204, 204));
        txtdni.setMaterialDesing(true);
        txtdni.setPlaceholder("Ingrese Dni");
        jPanel1.add(txtdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("DNI");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        txtcorreo.setForeground(new java.awt.Color(0, 0, 0));
        txtcorreo.setToolTipText("");
        txtcorreo.setBordeColorFocus(new java.awt.Color(251, 204, 52));
        txtcorreo.setBordeColorNoFocus(new java.awt.Color(204, 204, 204));
        txtcorreo.setCaretColor(new java.awt.Color(204, 204, 204));
        txtcorreo.setMaterialDesing(true);
        txtcorreo.setPlaceholder("Ingrese Correo");
        jPanel1.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("Correo");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setColorNormal(new java.awt.Color(255, 0, 0));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setText("Nombres");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresar1ActionPerformed
        agregar();
        limpiarTabla();
        listarTabla();
        limpiarFormulario();
    }//GEN-LAST:event_btnIngresar1ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminar();
        limpiarTabla();
        listarTabla();
        limpiarFormulario();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

        limpiarTabla();
        listarTabla();
        limpiarFormulario();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void jtablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablaMouseClicked
         int fila = jtabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila");
        } else {
            id = Integer.parseInt(jtabla.getValueAt(fila, 0).toString());
            String nombre = jtabla.getValueAt(fila, 1).toString();
            String apellidos = jtabla.getValueAt(fila, 2).toString();
            String direccion = jtabla.getValueAt(fila, 3).toString();
            String telefono = jtabla.getValueAt(fila, 4).toString();
            String dni= jtabla.getValueAt(fila, 5).toString();
            String correo = jtabla.getValueAt(fila, 6).toString();
            
            txtnombre.setText(nombre);
            
            txtapellidos.setText(apellidos);
            txtdireccion.setText(direccion);
             txtdni.setText(dni);
            txttelefono.setText(telefono);
            txtcorreo.setText(correo);
    }//GEN-LAST:event_jtablaMouseClicked
}  
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        actualizar();
        limpiarTabla();
        listarTabla();
        limpiarFormulario();
    }//GEN-LAST:event_btnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private LIB.FSButtonMD btnActualizar;
    private LIB.FSButtonMD btnEliminar;
    private LIB.FSButtonMD btnIngresar1;
    private LIB.FSButtonMD btnNuevo;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtabla;
    private LIB.FSTexFieldMD txtapellidos;
    private LIB.FSTexFieldMD txtcorreo;
    private LIB.FSTexFieldMD txtdireccion;
    private LIB.FSTexFieldMD txtdni;
    private LIB.FSTexFieldMD txtnombre;
    private LIB.FSTexFieldMD txttelefono;
    // End of variables declaration//GEN-END:variables

    void agregar() {
        String nombre = txtnombre.getText();
        String apellidos = txtapellidos.getText();
        String direccion = txtdireccion.getText();
        String telefono = txttelefono.getText();
        String dni = txtdni.getText();
        String correo= txtcorreo.getText();
        
        if (nombre.equals("") || apellidos.equals("") || direccion.equals("")  || telefono.equals("") || dni.equals("") || correo.equals("")) {
            JOptionPane.showMessageDialog(this, "Falta completar");
        } else {
            Object[] object = new Object[6];
            object[0] = nombre;
            object[1] = apellidos;
            object[2] = direccion;
            object[3] = telefono;
            object[4] = dni;
            object[5] = correo;
            clientedao.Agregar(object);
        }
    }

    void listarTabla() {
        List<Cliente> lst = clientedao.Listar();
        defaultTableModel = (DefaultTableModel) jtabla.getModel();
        Object[] object = new Object[7];
        for (int i = 0; i < lst.size(); i++) {
            object[0] = lst.get(i).getId_cliente();
            object[1] = lst.get(i).getNombre();
            object[2] = lst.get(i).getApellidos();
            object[3] = lst.get(i).getDireccion();
            object[4] = lst.get(i).getTelefono();
            object[5] = lst.get(i).getDni();
            object[6] = lst.get(i).getCorreo();
            defaultTableModel.addRow(object);
        }
        jtabla.setModel(defaultTableModel);
    }

    void actualizar() {
        int fila = jtabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila");
        } else {
        String nombre = txtnombre.getText();
        String apellidos = txtapellidos.getText();
        String direccion = txtdireccion.getText();
        String telefono = txttelefono.getText();
        String dni = txtdni.getText();
        String correo= txtcorreo.getText();
            Object[] object = new Object[7];
            object[0] = nombre;
            object[1] = apellidos;
            object[2] = direccion;
            object[3] = telefono;
            object[4] = dni;
            object[5] = correo;
            object[6] = id;
            clientedao.Actualizar(object);
        }
    }

    void eliminar() {
        int fila = jtabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila");
        } else {
            clientedao.Eliminar(id);
        }
    }

    void limpiarFormulario() {
       txtnombre.setText("");
       txtapellidos.setText("");
       txtdireccion.setText("");
       txttelefono.setText("");
       txtdni.setText("");
       txtcorreo.setText("");
    }

    void limpiarTabla() {
        for (int i = (defaultTableModel.getRowCount() - 1); i >= 0; i--) {
            defaultTableModel.removeRow(i);
        }
    }

}
