/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.dao.ConexionSQL;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
public class frmDetalledeBoleta extends javax.swing.JInternalFrame {
ConexionSQL cc= new ConexionSQL();
Connection con=cc.Conexion();
    DefaultTableModel modelo;
    public frmDetalledeBoleta() {
        initComponents();
        mostrarclientes();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 87, 536, 211));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("DETALLE DE BOLETA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtabla;
    // End of variables declaration//GEN-END:variables
void mostrarclientes()
    {
        String[]titulos={"ID BOLETA","FECHA","TOTAL","ID CLIENTE","ID EMPLEADO"} ;  
        String []Registros= new String[5];
        modelo=new DefaultTableModel(null,titulos);
        String Sql="SELECT * FROM r_boleta"; 
       
        try {
             Statement st = con.createStatement();
             ResultSet rs = st.executeQuery(Sql);
             while(rs.next())
             {
                 Registros[0]=rs.getString("id_boleta");  
                 Registros[1]=rs.getString("fecha");  
                 Registros[2]=rs.getString("total");  
                 Registros[3]=rs.getString("id_cliente");  
                 Registros[4]=rs.getString("id_empleado");  
                 
                 modelo.addRow(Registros);
             } 
             jtabla.setModel(modelo);
        } catch (SQLException ex) {
           
        }
 }
}
