/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.dao.EmpleadoDao;
import Modelo.entidad.Empleado;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PERSONAL
 */
public class frmEmpleado extends javax.swing.JInternalFrame {

    EmpleadoDao empleadodao = new EmpleadoDao();
    Empleado empleado = new Empleado();

    DefaultTableModel defaultTableModel = new DefaultTableModel();

    int id;

    public frmEmpleado() {
        initComponents();
        listarTabla();
    }
    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtnombre = new LIB.FSTexFieldMD();
        btnIngresar = new LIB.FSButtonMD();
        btnActualizar = new LIB.FSButtonMD();
        btnNuevo = new LIB.FSButtonMD();
        txtapellidos = new LIB.FSTexFieldMD();
        jLabel11 = new javax.swing.JLabel();
        txtdireccion = new LIB.FSTexFieldMD();
        jLabel12 = new javax.swing.JLabel();
        txttelefono = new LIB.FSTexFieldMD();
        jLabel13 = new javax.swing.JLabel();
        txtdni = new LIB.FSTexFieldMD();
        jLabel14 = new javax.swing.JLabel();
        txtcorreo = new LIB.FSTexFieldMD();
        jLabel15 = new javax.swing.JLabel();
        btnEliminar = new LIB.FSButtonMD();
        jLabel16 = new javax.swing.JLabel();
        txtusuario = new LIB.FSTexFieldMD();
        jLabel17 = new javax.swing.JLabel();
        cbPrivilegio = new javax.swing.JComboBox<>();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID EMPLEADO", "NOMBRES", "APELLIDOS", "DIRECCION", "TELEFONO", "DNI", "CORREO", "PRIVILEGIO", "USUARIO"
            }
        ));
        jtabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 20, 630, 310));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Registrar Empleado");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        txtnombre.setForeground(new java.awt.Color(0, 0, 0));
        txtnombre.setToolTipText("");
        txtnombre.setBordeColorFocus(new java.awt.Color(251, 204, 52));
        txtnombre.setBordeColorNoFocus(new java.awt.Color(204, 204, 204));
        txtnombre.setCaretColor(new java.awt.Color(204, 204, 204));
        txtnombre.setMaterialDesing(true);
        txtnombre.setPlaceholder("Ingrese Nombres");
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        btnIngresar.setBackground(new java.awt.Color(255, 0, 0));
        btnIngresar.setText("INGRESAR");
        btnIngresar.setColorNormal(new java.awt.Color(255, 0, 0));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, -1, -1));

        btnActualizar.setBackground(new java.awt.Color(255, 0, 0));
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.setColorNormal(new java.awt.Color(255, 0, 0));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, -1, -1));

        btnNuevo.setBackground(new java.awt.Color(255, 0, 0));
        btnNuevo.setText("NUEVO");
        btnNuevo.setColorNormal(new java.awt.Color(255, 0, 0));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, -1, -1));

        txtapellidos.setForeground(new java.awt.Color(0, 0, 0));
        txtapellidos.setToolTipText("");
        txtapellidos.setBordeColorFocus(new java.awt.Color(251, 204, 52));
        txtapellidos.setBordeColorNoFocus(new java.awt.Color(204, 204, 204));
        txtapellidos.setCaretColor(new java.awt.Color(204, 204, 204));
        txtapellidos.setMaterialDesing(true);
        txtapellidos.setPlaceholder("Ingrese Apellidos");
        jPanel1.add(txtapellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Apellidos");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        txtdireccion.setForeground(new java.awt.Color(0, 0, 0));
        txtdireccion.setToolTipText("");
        txtdireccion.setBordeColorFocus(new java.awt.Color(251, 204, 52));
        txtdireccion.setBordeColorNoFocus(new java.awt.Color(204, 204, 204));
        txtdireccion.setCaretColor(new java.awt.Color(204, 204, 204));
        txtdireccion.setMaterialDesing(true);
        txtdireccion.setPlaceholder("Ingrese Direccion");
        jPanel1.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("Direccion");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        txttelefono.setForeground(new java.awt.Color(0, 0, 0));
        txttelefono.setToolTipText("");
        txttelefono.setBordeColorFocus(new java.awt.Color(251, 204, 52));
        txttelefono.setBordeColorNoFocus(new java.awt.Color(204, 204, 204));
        txttelefono.setCaretColor(new java.awt.Color(204, 204, 204));
        txttelefono.setMaterialDesing(true);
        txttelefono.setPlaceholder("Ingrese Telefono");
        jPanel1.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Telefono");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        txtdni.setForeground(new java.awt.Color(0, 0, 0));
        txtdni.setToolTipText("");
        txtdni.setBordeColorFocus(new java.awt.Color(251, 204, 52));
        txtdni.setBordeColorNoFocus(new java.awt.Color(204, 204, 204));
        txtdni.setCaretColor(new java.awt.Color(204, 204, 204));
        txtdni.setMaterialDesing(true);
        txtdni.setPlaceholder("Ingrese Dni");
        jPanel1.add(txtdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("DNI");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        txtcorreo.setForeground(new java.awt.Color(0, 0, 0));
        txtcorreo.setToolTipText("");
        txtcorreo.setBordeColorFocus(new java.awt.Color(251, 204, 52));
        txtcorreo.setBordeColorNoFocus(new java.awt.Color(204, 204, 204));
        txtcorreo.setCaretColor(new java.awt.Color(204, 204, 204));
        txtcorreo.setMaterialDesing(true);
        txtcorreo.setPlaceholder("Ingrese Correo");
        jPanel1.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("Correo");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setColorNormal(new java.awt.Color(255, 0, 0));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setText("Nombres");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        txtusuario.setForeground(new java.awt.Color(0, 0, 0));
        txtusuario.setToolTipText("");
        txtusuario.setBordeColorFocus(new java.awt.Color(251, 204, 52));
        txtusuario.setBordeColorNoFocus(new java.awt.Color(204, 204, 204));
        txtusuario.setCaretColor(new java.awt.Color(204, 204, 204));
        txtusuario.setMaterialDesing(true);
        txtusuario.setPlaceholder("Ingrese Usuario");
        jPanel1.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 153, 153));
        jLabel17.setText("Usuario");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));

        cbPrivilegio.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        cbPrivilegio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Empleado" }));
        jPanel1.add(cbPrivilegio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 250, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        agregar();
        limpiarTabla();
        listarTabla();
        limpiarFormulario();
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        actualizar();
        limpiarTabla();
        listarTabla();
        limpiarFormulario();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

        limpiarTabla();
        listarTabla();
        limpiarFormulario();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminar();
        limpiarTabla();
        listarTabla();
        limpiarFormulario();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jtablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablaMouseClicked
            int fila = jtabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila");
        } else {
            id = Integer.parseInt(jtabla.getValueAt(fila, 0).toString());
            String nombre = jtabla.getValueAt(fila, 1).toString();
            String apellidos = jtabla.getValueAt(fila, 2).toString();
            String direccion= jtabla.getValueAt(fila, 3).toString();
            String  telefono= jtabla.getValueAt(fila, 4).toString();
            String dni = jtabla.getValueAt(fila, 5).toString();
         
            String correo = jtabla.getValueAt(fila, 6).toString();
            String usuario = jtabla.getValueAt(fila, 8).toString();
            String privilegio=jtabla.getValueAt(fila, 7).toString();
                    
            txtnombre.setText(nombre);
            txtapellidos.setText(apellidos);
            txtdni.setText(dni);
            txtdireccion.setText(direccion);
            txttelefono.setText(telefono);
            txtcorreo.setText(correo);
            txtusuario.setText(usuario);
            cbPrivilegio.setSelectedItem(privilegio);
           }   
    }//GEN-LAST:event_jtablaMouseClicked

    void agregar() {
        String nombre = txtnombre.getText();
        String apellidos = txtapellidos.getText();
        String direccion = txtdireccion.getText();
        String telefono = txttelefono.getText();
        String dni = txtdni.getText();
        String correo = txtcorreo.getText();
        String privilegio = cbPrivilegio.getSelectedItem().toString();
        String usuario = txtusuario.getText();
        
        if (nombre.equals("") || apellidos.equals("") || direccion.equals("") || telefono.equals("")  || dni.equals("") || correo.equals("") || usuario.equals("")) {
            JOptionPane.showMessageDialog(this, "Falta completar");
        } else {
            Object[] object = new Object[8];
            object[0] = nombre;
            object[1] = apellidos;
            object[2] = direccion;
            object[3] = telefono;
            object[4] = dni;
            object[5] = correo;
            object[6] = privilegio;
            object[7] = usuario;
            empleadodao.Agregar(object);
        }
    }

    void listarTabla() {
        List<Empleado> lista = empleadodao.Listar();
        defaultTableModel = (DefaultTableModel) jtabla.getModel();
        Object[] object = new Object[9];
        for (int i = 0; i < lista.size(); i++) {
            object[0] = lista.get(i).getId_empleado();
            object[1] = lista.get(i).getNombre();
            object[2] = lista.get(i).getApellidos();
            object[3] = lista.get(i).getDireccion();
            object[4] = lista.get(i).getTelefono();
            object[5] = lista.get(i).getDni();
            object[6] = lista.get(i).getCorreo();
            object[7] = lista.get(i).getPrivilegio();
            object[8] = lista.get(i).getUsuario();
            defaultTableModel.addRow(object);
        }
        jtabla.setModel(defaultTableModel);
    }

    void actualizar() {
        int fila = jtabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila");
        } else {
        String nombre = txtnombre.getText();
        String apellidos = txtapellidos.getText();
        String direccion = txtdireccion.getText();
        String telefono = txttelefono.getText();
        String dni = txtdni.getText();
        String correo = txtcorreo.getText();
        String privilegio = cbPrivilegio.getSelectedItem().toString();
        String usuario = txtusuario.getText();
            Object[] object = new Object[9];
           object[0] = nombre;
            object[1] = apellidos;
            object[2] = direccion;
            object[3] = telefono;
            object[4] = dni;
            object[5] = correo;
            object[6] = privilegio;
            object[7] = usuario;
            object[8] = id;
            empleadodao.Actualizar(object);
        }
    }

    void eliminar() {
        int fila = jtabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila");
        } else {
            empleadodao.Eliminar(id);
        }
    }

    void limpiarFormulario() {
          txtnombre.setText("");
         txtapellidos.setText("");
        txtdireccion.setText("");
        txttelefono.setText("");
         txtdni.setText("");
         txtcorreo.setText("");
         cbPrivilegio.setSelectedItem(0);
        txtusuario.setText("");
    }

    void limpiarTabla() {
        for (int i = (defaultTableModel.getRowCount() - 1); i >= 0; i--) {
            defaultTableModel.removeRow(i);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private LIB.FSButtonMD btnActualizar;
    private LIB.FSButtonMD btnEliminar;
    private LIB.FSButtonMD btnIngresar;
    private LIB.FSButtonMD btnNuevo;
    private javax.swing.JComboBox<String> cbPrivilegio;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtabla;
    private LIB.FSTexFieldMD txtapellidos;
    private LIB.FSTexFieldMD txtcorreo;
    private LIB.FSTexFieldMD txtdireccion;
    private LIB.FSTexFieldMD txtdni;
    private LIB.FSTexFieldMD txtnombre;
    private LIB.FSTexFieldMD txttelefono;
    private LIB.FSTexFieldMD txtusuario;
    // End of variables declaration//GEN-END:variables

}
