/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.dao.FinanzasDao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Modelo.entidad.Finanzas;
import java.text.SimpleDateFormat;

import java.util.List;


/**
 *
 * @author PERSONAL
 */
public class frmFinanzas extends javax.swing.JInternalFrame {

    FinanzasDao finanzasdao = new FinanzasDao();
    Finanzas finanzas = new Finanzas();
   
    DefaultTableModel defaultTableModel = new DefaultTableModel();
    SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
    int id;
    
    
    public frmFinanzas() {
        initComponents();
        listarTabla();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla = new javax.swing.JTable();
        fech = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtmonto = new LIB.FSTexFieldMD();
        jLabel7 = new javax.swing.JLabel();
        txtasunto = new LIB.FSTexFieldMD();
        btnIngresar = new LIB.FSButtonMD();
        btnEliminar = new LIB.FSButtonMD();
        btnEliminar1 = new LIB.FSButtonMD();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, -1, 140));

        jtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ASUNTO", "MONTO", "FECHA"
            }
        ));
        jtabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtabla);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 395, 275));
        jPanel3.add(fech, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 250, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("REGISTRO");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Fecha");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        txtmonto.setForeground(new java.awt.Color(0, 0, 0));
        txtmonto.setToolTipText("");
        txtmonto.setBordeColorFocus(new java.awt.Color(251, 204, 52));
        txtmonto.setBordeColorNoFocus(new java.awt.Color(204, 204, 204));
        txtmonto.setCaretColor(new java.awt.Color(204, 204, 204));
        txtmonto.setMaterialDesing(true);
        txtmonto.setPlaceholder("Ingrese Usuario");
        jPanel3.add(txtmonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Monto");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 20));

        txtasunto.setForeground(new java.awt.Color(0, 0, 0));
        txtasunto.setToolTipText("");
        txtasunto.setBordeColorFocus(new java.awt.Color(251, 204, 52));
        txtasunto.setBordeColorNoFocus(new java.awt.Color(204, 204, 204));
        txtasunto.setCaretColor(new java.awt.Color(204, 204, 204));
        txtasunto.setMaterialDesing(true);
        txtasunto.setPlaceholder("Ingrese Usuario");
        jPanel3.add(txtasunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        btnIngresar.setBackground(new java.awt.Color(255, 0, 0));
        btnIngresar.setText("REGISTRAR");
        btnIngresar.setColorNormal(new java.awt.Color(255, 0, 0));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel3.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminar.setText("ACTUALIZAR");
        btnEliminar.setColorNormal(new java.awt.Color(255, 0, 0));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        btnEliminar1.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminar1.setText("ELIMINAR");
        btnEliminar1.setColorNormal(new java.awt.Color(255, 0, 0));
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Asunto");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
       agregar();
        listarTabla();
        
        limpiarFormulario();
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
      actualizar();
        limpiarTabla();
        listarTabla();
        limpiarFormulario();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
          eliminar();
        limpiarTabla();
        listarTabla();
        limpiarFormulario();
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void jtablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablaMouseClicked
        int fila = jtabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila");
        } else {
            id = Integer.parseInt(jtabla.getValueAt(fila, 0).toString());
            String asunto = jtabla.getValueAt(fila, 1).toString();
            String monto = jtabla.getValueAt(fila, 2).toString();
            String fech = jtabla.getValueAt(fila, 3).toString();
            
            txtasunto.setText(asunto);
            txtmonto.setText(monto);
           
          }    
          
    }//GEN-LAST:event_jtablaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private LIB.FSButtonMD btnEliminar;
    private LIB.FSButtonMD btnEliminar1;
    private LIB.FSButtonMD btnIngresar;
    private com.toedter.calendar.JDateChooser fech;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtabla;
    private LIB.FSTexFieldMD txtasunto;
    private LIB.FSTexFieldMD txtmonto;
    // End of variables declaration//GEN-END:variables
void agregar(){
        String asunto = txtasunto.getText();
        Double monto = Double.parseDouble(txtmonto.getText());
         String fecha = f.format(fech.getDate());
        
        
        if (asunto.equals("") || monto.equals("") ) {
            JOptionPane.showMessageDialog(this, "Falta completar");
        } else {
            Object[] object = new Object[6];
            object[0] = asunto;
            object[1] = monto;
            object[2] = fecha;
      
            finanzasdao.Agregar(object);
        }
}

void listarTabla() {
        List<Finanzas> lst = finanzasdao.Listar();
        defaultTableModel = (DefaultTableModel) jtabla.getModel();
        Object[] object = new Object[4];
        for (int i = 0; i < lst.size(); i++) {
            object[0] = lst.get(i).getId_finanzas();
            object[1] = lst.get(i).getAsunto();
            object[2] = lst.get(i).getMonto();
            object[3] = lst.get(i).getFecha();
            
            defaultTableModel.addRow(object);
        }
        jtabla.setModel(defaultTableModel);
    }

void actualizar() {
        int fila = jtabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila");
        } else {
            String asunto = txtasunto.getText();
            Double monto = Double.parseDouble(txtmonto.getText());
            String fecha = f.format(fech.getDate());
            Object[] object = new Object[7];
            object[0] = asunto;
            object[1] = monto;
            object[2] = fecha;
            
            object[3] = id;
            finanzasdao.Actualizar(object);
        }
}

void eliminar() {
        int fila = jtabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila");
        } else {
            finanzasdao.Eliminar(id);
        }
    }
void limpiarFormulario() {
       txtasunto.setText("");
       txtmonto.setText("");
       
       
    }

    void limpiarTabla() {
        for (int i = (defaultTableModel.getRowCount() - 1); i >= 0; i--) {
            defaultTableModel.removeRow(i);
        }
    }
     
    
    
}
