/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.dao.ProveedoresDao;
import Modelo.entidad.Proveedores;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PERSONAL
 */
public class frmProveedores extends javax.swing.JInternalFrame {

    ProveedoresDao proveedordao = new ProveedoresDao();
    Proveedores proveedor = new Proveedores();

    DefaultTableModel defaultTableModel = new DefaultTableModel();

    int id;
    public frmProveedores() {
        initComponents();
        listarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla = new javax.swing.JTable();
        txtnombre = new LIB.FSTexFieldMD();
        jLabel16 = new javax.swing.JLabel();
        txtruc = new LIB.FSTexFieldMD();
        jLabel17 = new javax.swing.JLabel();
        txtrazon = new LIB.FSTexFieldMD();
        jLabel18 = new javax.swing.JLabel();
        txtdireccion = new LIB.FSTexFieldMD();
        jLabel19 = new javax.swing.JLabel();
        txtcorreo = new LIB.FSTexFieldMD();
        jLabel20 = new javax.swing.JLabel();
        txttelefono = new LIB.FSTexFieldMD();
        jLabel21 = new javax.swing.JLabel();
        btnIngresar1 = new LIB.FSButtonMD();
        btnNuevo = new LIB.FSButtonMD();
        btnActualizar = new LIB.FSButtonMD();
        btnEliminar = new LIB.FSButtonMD();
        jLabel22 = new javax.swing.JLabel();

        setClosable(true);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtabla.setBackground(new java.awt.Color(204, 255, 255));
        jtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID PROVEEDOR", "NOMBRES", "RUC", "RAZON SOCIAL", "DIRECCION", "TELEFONO", "CORREO"
            }
        ));
        jtabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtabla);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 690, 160));

        txtnombre.setForeground(new java.awt.Color(0, 0, 0));
        txtnombre.setToolTipText("");
        txtnombre.setBordeColorFocus(new java.awt.Color(251, 204, 52));
        txtnombre.setBordeColorNoFocus(new java.awt.Color(204, 204, 204));
        txtnombre.setCaretColor(new java.awt.Color(204, 204, 204));
        txtnombre.setMaterialDesing(true);
        txtnombre.setPlaceholder("Ingrese Nombres");
        jPanel2.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setText("Proveedores");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        txtruc.setForeground(new java.awt.Color(0, 0, 0));
        txtruc.setToolTipText("");
        txtruc.setBordeColorFocus(new java.awt.Color(251, 204, 52));
        txtruc.setBordeColorNoFocus(new java.awt.Color(204, 204, 204));
        txtruc.setCaretColor(new java.awt.Color(204, 204, 204));
        txtruc.setMaterialDesing(true);
        txtruc.setPlaceholder("Ingrese Nombres");
        jPanel2.add(txtruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 153, 153));
        jLabel17.setText("Ruc");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        txtrazon.setForeground(new java.awt.Color(0, 0, 0));
        txtrazon.setToolTipText("");
        txtrazon.setBordeColorFocus(new java.awt.Color(251, 204, 52));
        txtrazon.setBordeColorNoFocus(new java.awt.Color(204, 204, 204));
        txtrazon.setCaretColor(new java.awt.Color(204, 204, 204));
        txtrazon.setMaterialDesing(true);
        txtrazon.setPlaceholder("Ingrese Nombres");
        jPanel2.add(txtrazon, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 153, 153));
        jLabel18.setText("Razon Social");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        txtdireccion.setForeground(new java.awt.Color(0, 0, 0));
        txtdireccion.setToolTipText("");
        txtdireccion.setBordeColorFocus(new java.awt.Color(251, 204, 52));
        txtdireccion.setBordeColorNoFocus(new java.awt.Color(204, 204, 204));
        txtdireccion.setCaretColor(new java.awt.Color(204, 204, 204));
        txtdireccion.setMaterialDesing(true);
        txtdireccion.setPlaceholder("Ingrese Nombres");
        jPanel2.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 153, 153));
        jLabel19.setText("Direccion");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, -1));

        txtcorreo.setForeground(new java.awt.Color(0, 0, 0));
        txtcorreo.setToolTipText("");
        txtcorreo.setBordeColorFocus(new java.awt.Color(251, 204, 52));
        txtcorreo.setBordeColorNoFocus(new java.awt.Color(204, 204, 204));
        txtcorreo.setCaretColor(new java.awt.Color(204, 204, 204));
        txtcorreo.setMaterialDesing(true);
        txtcorreo.setPlaceholder("Ingrese Nombres");
        jPanel2.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 153, 153));
        jLabel20.setText("Correo");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));

        txttelefono.setForeground(new java.awt.Color(0, 0, 0));
        txttelefono.setToolTipText("");
        txttelefono.setBordeColorFocus(new java.awt.Color(251, 204, 52));
        txttelefono.setBordeColorNoFocus(new java.awt.Color(204, 204, 204));
        txttelefono.setCaretColor(new java.awt.Color(204, 204, 204));
        txttelefono.setMaterialDesing(true);
        txttelefono.setPlaceholder("Ingrese Nombres");
        jPanel2.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 153, 153));
        jLabel21.setText("Telefono");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, -1, -1));

        btnIngresar1.setBackground(new java.awt.Color(255, 0, 0));
        btnIngresar1.setText("INGRESAR");
        btnIngresar1.setColorNormal(new java.awt.Color(255, 0, 0));
        btnIngresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresar1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnIngresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));

        btnNuevo.setBackground(new java.awt.Color(255, 0, 0));
        btnNuevo.setText("NUEVO");
        btnNuevo.setColorNormal(new java.awt.Color(255, 0, 0));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, -1, -1));

        btnActualizar.setBackground(new java.awt.Color(255, 0, 0));
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.setColorNormal(new java.awt.Color(255, 0, 0));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setColorNormal(new java.awt.Color(255, 0, 0));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 153, 153));
        jLabel22.setText("Nombres");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablaMouseClicked
        int fila = jtabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila");
        } else {
            id = Integer.parseInt(jtabla.getValueAt(fila, 0).toString());
            String nombre = jtabla.getValueAt(fila, 1).toString();
            String ruc = jtabla.getValueAt(fila, 2).toString();
            String razon= jtabla.getValueAt(fila, 3).toString();
            String direccion = jtabla.getValueAt(fila, 4).toString();
            String telefono = jtabla.getValueAt(fila, 5).toString();
         
            String correo = jtabla.getValueAt(fila, 6).toString();
            txtnombre.setText(nombre);
            txtruc.setText(ruc);
            txtrazon.setText(razon);
            txtdireccion.setText(direccion);
            txttelefono.setText(telefono);
            txtcorreo.setText(correo);
           }   
    }//GEN-LAST:event_jtablaMouseClicked

    private void btnIngresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresar1ActionPerformed
        agregar();
        limpiarTabla();
        listarTabla();
        limpiarFormulario();
    }//GEN-LAST:event_btnIngresar1ActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

        limpiarTabla();
        listarTabla();
        limpiarFormulario();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        actualizar();
        limpiarTabla();
        listarTabla();
        limpiarFormulario();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminar();
        limpiarTabla();
        listarTabla();
        limpiarFormulario();
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private LIB.FSButtonMD btnActualizar;
    private LIB.FSButtonMD btnEliminar;
    private LIB.FSButtonMD btnIngresar1;
    private LIB.FSButtonMD btnNuevo;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtabla;
    private LIB.FSTexFieldMD txtcorreo;
    private LIB.FSTexFieldMD txtdireccion;
    private LIB.FSTexFieldMD txtnombre;
    private LIB.FSTexFieldMD txtrazon;
    private LIB.FSTexFieldMD txtruc;
    private LIB.FSTexFieldMD txttelefono;
    // End of variables declaration//GEN-END:variables
 void agregar() {
        String nombre = txtnombre.getText();
        String ruc = txtruc.getText();
        String razon= txtrazon.getText();
        String direccion = txtdireccion.getText();
        String telefono = txttelefono.getText();
        String correo= txtcorreo.getText();
        
        if (nombre.equals("") || ruc.equals("") || direccion.equals("")  || telefono.equals("") || razon.equals("") || correo.equals("")) {
            JOptionPane.showMessageDialog(this, "Falta completar");
        } else {
            Object[] object = new Object[6];
            object[0] = nombre;
            object[1] = ruc;
            object[2] = razon;
            object[3] = direccion;
            object[4] = telefono;
          
            object[5] = correo;
            proveedordao.Agregar(object);
        }
    }

    void listarTabla() {
        List<Proveedores> lst = proveedordao.Listar();
        defaultTableModel = (DefaultTableModel) jtabla.getModel();
        Object[] object = new Object[7];
        for (int i = 0; i < lst.size(); i++) {
            object[0] = lst.get(i).getId_proveedor();
            object[1] = lst.get(i).getNombres();
            object[2] = lst.get(i).getRuc();
            object[3] = lst.get(i).getRazonsocial();
            object[4] = lst.get(i).getDireccion();
            object[5] = lst.get(i).getTelefono();
            object[6] = lst.get(i).getCorreo();
            defaultTableModel.addRow(object);
        }
        jtabla.setModel(defaultTableModel);
    }

    void actualizar() {
        int fila = jtabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila");
        } else {
         String nombre = txtnombre.getText();
        String ruc = txtruc.getText();
        String razon= txtrazon.getText();
        String direccion = txtdireccion.getText();
        String telefono = txttelefono.getText();
        String correo= txtcorreo.getText();
            Object[] object = new Object[7];
            object[0] = nombre;
            object[1] = ruc;
            object[2] = razon;
            object[3] = direccion;
            object[4] = telefono;
            object[5] = correo;
            object[6] = id;
            proveedordao.Actualizar(object);
        }
    }

    void eliminar() {
        int fila = jtabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila");
        } else {
            proveedordao.Eliminar(id);
        }
    }

    void limpiarFormulario() {
       txtnombre.setText("");
       txtruc.setText("");
       txtrazon.setText("");
       txtdireccion.setText("");
       txttelefono.setText("");
       txtcorreo.setText("");
    }

    void limpiarTabla() {
        for (int i = (defaultTableModel.getRowCount() - 1); i >= 0; i--) {
            defaultTableModel.removeRow(i);
        }
    }

}
