/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.dao.ProductoDao;
import Modelo.entidad.Producto;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PERSONAL
 */
public class Productos extends javax.swing.JInternalFrame {

    ProductoDao productodao = new ProductoDao();
    Producto producto = new Producto();

    DefaultTableModel defaultTableModel = new DefaultTableModel();

    int id;
    public Productos() {
        initComponents();
        listarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnNuevo = new LIB.FSButtonMD();
        txtnombre = new LIB.FSTexFieldMD();
        jLabel5 = new javax.swing.JLabel();
        txtprecio = new LIB.FSTexFieldMD();
        jLabel6 = new javax.swing.JLabel();
        txtstock = new LIB.FSTexFieldMD();
        jLabel7 = new javax.swing.JLabel();
        btnIngresar = new LIB.FSButtonMD();
        btnActualizar = new LIB.FSButtonMD();
        jLabel8 = new javax.swing.JLabel();
        btnEliminar = new LIB.FSButtonMD();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla = new javax.swing.JTable();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNuevo.setBackground(new java.awt.Color(255, 0, 0));
        btnNuevo.setText("NUEVO");
        btnNuevo.setColorNormal(new java.awt.Color(255, 0, 0));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        txtnombre.setForeground(new java.awt.Color(0, 0, 0));
        txtnombre.setToolTipText("");
        txtnombre.setBordeColorFocus(new java.awt.Color(251, 204, 52));
        txtnombre.setBordeColorNoFocus(new java.awt.Color(204, 204, 204));
        txtnombre.setCaretColor(new java.awt.Color(204, 204, 204));
        txtnombre.setMaterialDesing(true);
        txtnombre.setPlaceholder("Ingrese Producto");
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Registro de Productos");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        txtprecio.setForeground(new java.awt.Color(0, 0, 0));
        txtprecio.setToolTipText("");
        txtprecio.setBordeColorFocus(new java.awt.Color(251, 204, 52));
        txtprecio.setBordeColorNoFocus(new java.awt.Color(204, 204, 204));
        txtprecio.setCaretColor(new java.awt.Color(204, 204, 204));
        txtprecio.setMaterialDesing(true);
        txtprecio.setPlaceholder("Ingrese Precio");
        jPanel1.add(txtprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Precio");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        txtstock.setForeground(new java.awt.Color(0, 0, 0));
        txtstock.setToolTipText("");
        txtstock.setBordeColorFocus(new java.awt.Color(251, 204, 52));
        txtstock.setBordeColorNoFocus(new java.awt.Color(204, 204, 204));
        txtstock.setCaretColor(new java.awt.Color(204, 204, 204));
        txtstock.setMaterialDesing(true);
        txtstock.setPlaceholder("Ingrese Cantidad");
        jPanel1.add(txtstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Stock");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        btnIngresar.setBackground(new java.awt.Color(255, 0, 0));
        btnIngresar.setText("INGRESAR");
        btnIngresar.setColorNormal(new java.awt.Color(255, 0, 0));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        btnActualizar.setBackground(new java.awt.Color(255, 0, 0));
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.setColorNormal(new java.awt.Color(255, 0, 0));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Producto");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setColorNormal(new java.awt.Color(255, 0, 0));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        jtabla.setBackground(new java.awt.Color(204, 204, 204));
        jtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID PRODUCTO", "PRODUCTO", "PRECIO", "STOCK"
            }
        ));
        jtabla.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jtabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 420, 489));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablaMouseClicked
       int fila = jtabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila");
        } else {
            id = Integer.parseInt(jtabla.getValueAt(fila, 0).toString());
            String nombre = jtabla.getValueAt(fila, 1).toString();
            String precio = jtabla.getValueAt(fila, 2).toString();
            String stock = jtabla.getValueAt(fila, 3).toString();
            
            txtnombre.setText(nombre);
            txtprecio.setText(precio);
            txtstock.setText(stock);
            
        }
    }//GEN-LAST:event_jtablaMouseClicked

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        
        
        limpiarTabla();
        listarTabla();
        limpiarFormulario();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
         agregar();
        limpiarTabla();
        listarTabla();
        limpiarFormulario();
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        actualizar();
        limpiarTabla();
        listarTabla();
        limpiarFormulario();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminar();
        limpiarTabla();
        listarTabla();
        limpiarFormulario();
    }//GEN-LAST:event_btnEliminarActionPerformed
 void agregar() {
        String nombre = txtnombre.getText();
        String precio = txtprecio.getText();
        String stock = txtstock.getText();
        
        if (nombre.equals("") || precio.equals("") || stock.equals("")) {
            JOptionPane.showMessageDialog(this, "Falta completar");
        } else {
            Object[] object = new Object[3];
            object[0] = nombre;
            object[1] = precio;
            object[2] = stock;
            
            productodao.Agregar(object);
        }
    }

    void listarTabla() {
        List<Producto> lista = productodao.Listar();
        defaultTableModel = (DefaultTableModel) jtabla.getModel();
        Object[] object = new Object[4];
        for (int i = 0; i < lista.size(); i++) {
            object[0] = lista.get(i).getId_producto();
            object[1] = lista.get(i).getNombre();
            object[2] = lista.get(i).getPrecio();
            object[3] = lista.get(i).getStock();
            
            defaultTableModel.addRow(object);
        }
        jtabla.setModel(defaultTableModel);
    }

    void actualizar() {
        int fila = jtabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila");
        } else {
            String nombre = txtnombre.getText();
            String precio = txtprecio.getText();
            String stock = txtstock.getText();
            
            Object[] object = new Object[4];
            object[0] = nombre;
            object[1] = precio;
            object[2] = stock;
            object[3] = id;
            productodao.Actualizar(object);
        }
    }

    void eliminar() {
        int fila = jtabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila");
        } else {
            productodao.Eliminar(id);
        }
    }

    void limpiarFormulario() {
        txtnombre.setText("");
        txtprecio.setText("");
        txtstock.setText("");
        txtnombre.requestFocus();
    }

    void limpiarTabla() {
        for (int i = (defaultTableModel.getRowCount() - 1); i >= 0; i--) {
            defaultTableModel.removeRow(i);
        }
        }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private LIB.FSButtonMD btnActualizar;
    private LIB.FSButtonMD btnEliminar;
    private LIB.FSButtonMD btnIngresar;
    private LIB.FSButtonMD btnNuevo;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtabla;
    private LIB.FSTexFieldMD txtnombre;
    private LIB.FSTexFieldMD txtprecio;
    private LIB.FSTexFieldMD txtstock;
    // End of variables declaration//GEN-END:variables

}
